% Record
v=VideoWriter('project1.avi');
v.FrameRate=60;
open(v);
 
% Create a figure
clf(figure(1),'reset');
figure(1);
set(gcf,'menubar','none');
set(gcf,'unit','normalized','position',[0.2,0.2,0.6,0.6]);
set(gcf,'defaultuicontrolunits','normalized');
set(gcf,'defaultuicontrolhorizontal','left');
set(gcf,'defaultuicontrolfontsize',12);
% Create a title
uicontrol(gcf,'style','text','string','Car Animation',...
        'position',[0.42,0.9,0.2,0.05],'fontsize',18);
% Create Axis
h_axes=axes('position',[0.3,0.23,0.4,0.6]);
axis equal;
htitle=title('Car Simulation');
% Create Initalization for user's choice
uicontrol(gcf,'style','text','string','Initalization',...
        'position',[0.07,0.76,0.15,0.1],'fontsize',14);
uicontrol(gcf,'style','text','string','Width Of The Street (Range:(0,0.5))',...
        'position',[0.03,0.7,0.2,0.1],'fontsize',8);
UIStreetWidth=uicontrol(gcf,'style','edit','string','0.1',...
        'position',[0.03,0.71,0.2,0.03],'fontsize',8,...
        'callback',[...
        'set(UIPeriodChangeRedLight,"String",num2str(250*(str2double(get(UIStreetWidth,"string"))*2+0.1)));',...
        'set(UIPeriodChangeGreenLight,"String",num2str(150*(str2double(get(UIStreetWidth,"string"))*2+0.1)));',...
        'set(UIPeriodChangeYellowLight,"String",num2str(100*(str2double(get(UIStreetWidth,"string"))*2+0.1)));']);
uicontrol(gcf,'style','text','string','The Total Number Of Cars (Range:(10,1000))',...
        'position',[0.03,0.6,0.2,0.1],'fontsize',8);
UICarNumber=uicontrol(gcf,'style','edit','string','30',...
        'position',[0.03,0.61,0.2,0.03],'fontsize',8);
uicontrol(gcf,'style','text','string','The Length of Interval (Range:(0,0.1))',...
        'position',[0.03,0.5,0.2,0.1],'fontsize',8);
UIIntervalLength=uicontrol(gcf,'style','edit','string','0.01',...
        'position',[0.03,0.51,0.2,0.03],'fontsize',8);
uicontrol(gcf,'style','text','string','The Possibility Of Omitting Light (Range:[0,1])',...
        'position',[0.03,0.4,0.2,0.1],'fontsize',8);
UICarPossibilityOmitLight=uicontrol(gcf,'style','edit','string','0',...
        'position',[0.03,0.41,0.2,0.03],'fontsize',8);
uicontrol(gcf,'style','text','string','Period Of Changing Light (Range:(1,10000)) (Order:Red,Green,Yellow)',...
        'position',[0.75,0.57,0.2,0.1],'fontsize',10);
UIPeriodChangeRedLight=uicontrol(gcf,'style','edit','string','75',...
        'position',[0.75,0.55,0.065,0.03],'fontsize',8);
UIPeriodChangeGreenLight=uicontrol(gcf,'style','edit','string','45',...
        'position',[0.8175,0.55,0.065,0.03],'fontsize',8);
UIPeriodChangeYellowLight=uicontrol(gcf,'style','edit','string','30',...
        'position',[0.885,0.55,0.065,0.03],'fontsize',8);
% Create a button for Starting The Game
GameStart=uicontrol(gcf,'style','pushbutton','string','Start!',...
        'position',[0.08,0.24,0.1,0.05],'fontsize',12,'horizontal','center',...
        'callback',[...
        'AnimationLog.String="CarLog: ";',...
        'cla;',...
        'Game(UIStreetWidth,UICarNumber,UIPeriodChangeRedLight,UIPeriodChangeGreenLight,UIPeriodChangeYellowLight,UIIntervalLength,UICarPossibilityOmitLight,AnimationLog);']);
uicontrol(gcf,'style','pushbutton','string','Pause',...
        'position',[0.05,0.18,0.08,0.05],'fontsize',12,'horizontal','center',...
        'callback','waitforbuttonpress;');
uicontrol(gcf,'style','pushbutton','string','Restart',...
        'position',[0.13,0.18,0.08,0.05],'fontsize',12,'horizontal','center');
% Create a Dashboard
AnimationLog=uicontrol(gcf,'style','text','string',"CarLog:",...
                        'position',[0.2,0,0.6,0.18],'backgroundcolor','white',...
                        'fontsize',8);
