function ex3()
    product=[struct('Type','Jumpers','Color','Blue','Quantity',2,'Bought',2005),...
            struct('Type','Jumpers','Color','Brown','Quantity',3,'Bought',2013),...
            struct('Type','Jumpers','Color','Green','Quantity',5,'Bought',2015),...
            struct('Type','Trousers','Color','Black','Quantity',3,'Bought',2012),...
            struct('Type','Trousers','Color','Grey','Quantity',2,'Bought',2011),...
            struct('Type','Trousers','Color','White','Quantity',1,'Bought',2013),...
            struct('Type','T-shirts','Color','Blue','Quantity',1,'Bought',2010),...
            struct('Type','T-shirts','Color','Green','Quantity',2,'Bought',2014),...
            struct('Type','T-shirts','Color','Red','Quantity',3,'Bought',2012),...
            struct('Type','T-shirts','Color','White','Quantity',2,'Bought',2008),...
            struct('Type','T-shirts','Color','Yellow','Quantity',1,'Bought',2012)];
    disp("Jumpers Green");
    sum=0;
    for i=1:11
        sum=sum+2021-product(i).Bought+1;
    end
    disp(floor(sum/11));
end